names = [('Noel', 'Schieber'),
('Danyelle', 'Scranton'),
('Dori', 'Marone'),
('Ernie', 'Guido'),
('Ulysses', 'Jones'),
('Barbie', 'Aune'),
('Ines', 'Wilkens'),
('Bradley', 'Raub'),
('Maia', 'Barboza'),
('Daphne', 'Jamal'),
('Merlin', 'Albano'),
('Janeen', 'Heard'),
('Dillon', 'Jones'),
('Theressa', 'Siddiqui'),
('Lucila', 'Stahly'),
('Chara', 'Battista'),
('Martina', 'Mckibben'),
('Suzanna', 'Allman'),
('Mariette', 'Pelosi'),
('Karleen', 'Piel'),
('Alaina', 'Capers'),
('Eleanore', 'Flannigan'),
('Drucilla', 'Rudnicki'),
('Idalia', 'Bridgers'),
('Dolly', 'Tipler'),
('Margarito', 'Jones'),
('Junie', 'Schreffler'),
('Li', 'Shellhammer'),
('Myron', 'Pound'),
('Bev', 'Archer'),
('Amal', 'Oldham'),
('Ardell', 'Cantley'),
('Dede', 'Hastie'),
('Sherika', 'Jones'),
('Amira', 'Veatch'),
('Bobette', 'Nokes'),
('Olinda', 'Dipiazza'),
('Norman', 'Prock'),
('Toccara', 'Pohlmann'),
('Vinnie', 'Gunnells'),
('Letha', 'Baggs'),
('Carlyn', 'Kring'),
('Jesusita', 'Rasmusson'),
('Suzanne', 'Giebler'),
('Edna', 'Jones'),
('Ruth', 'Feggins'),
('Siu', 'Morganti'),
('Debby', 'Schlabach'),
('Emily', 'Williamson'),
('Vonda', 'Jones')]

'''
5.19 (Finding the People with a Specified Last Name) Create a list of tuples containing
first and last names. Use filter to locate the tuples containing the last name Jones. 
Ensure that several tuples in your list have that last name.
'''
searched_last_name = 'Jones'
print(list(filter(lambda x: (x[1]).lower() == searched_last_name.lower(), names)))